#ifndef CORE_BRIDGE_H
#define CORE_BRIDGE_H

/* Generated with cbindgen:0.29.4 */

/* This file is auto-generated by cbindgen, do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * FFI 错误码
 */
enum ErrorCode
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * 成功
     */
    ERROR_CODE_ERROR_CODE_OK = 0,
    /**
     * 参数无效
     */
    ERROR_CODE_ERROR_CODE_INVALID_ARG = -1,
    /**
     * 空指针
     */
    ERROR_CODE_ERROR_CODE_NULL_POINTER = -2,
    /**
     * UTF-8 解码失败
     */
    ERROR_CODE_ERROR_CODE_UTF8 = -3,
    /**
     * 未初始化
     */
    ERROR_CODE_ERROR_CODE_NOT_INITIALIZED = -4,
    /**
     * 已经初始化
     */
    ERROR_CODE_ERROR_CODE_ALREADY_INITIALIZED = -5,
    /**
     * 内部错误（panic / 异常）
     */
    ERROR_CODE_ERROR_CODE_INTERNAL = -100,
    /**
     * 未实现（该功能在当前 phase 不可用）
     */
    ERROR_CODE_ERROR_CODE_NOT_IMPLEMENTED = -101,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum ErrorCode ErrorCode;
#else
typedef int32_t ErrorCode;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * 库版本号
 *
 * 返回 C 字符串，Dart 端需 `calloc.free()` 释放。
 *
 * # Safety
 *
 * 调用方必须保证返回的指针最终用 `libc::free()` 释放。
 */
char *proxy_version(void);

/**
 * 初始化代理核心。
 *
 * # Arguments
 *
 * * `home_dir` - 工作目录（通常是 app 的 files 目录）
 * * `version` - 应用版本号
 * * `sdk` - 平台 SDK 版本（Android API Level 或 iOS 版本号 * 100）
 *
 * # Returns
 *
 * 0 成功，非 0 失败。
 *
 * # Safety
 *
 * `home_dir` 和 `version` 必须是合法的 UTF-8 C 字符串（可为 NULL，但会导致错误）。
 */
int32_t proxy_init(const char *home_dir,
                   const char *version,
                   int32_t sdk);

/**
 * 关闭代理核心，释放资源。
 */
int32_t proxy_shutdown(void);

/**
 * 查询当前状态（JSON 字符串）。
 *
 * 返回的指针需要 `libc::free()` 释放。
 *
 * # Safety
 *
 * 同上。
 */
char *proxy_query_state(void);

/**
 * 获取最后一次错误的描述（人类可读）。
 *
 * 返回的指针需要 `libc::free()` 释放。
 */
char *proxy_last_error_message(int32_t code);

/**
 * 简单的 ping 接口，验证 FFI 链路。
 *
 * 输入字符串，输出 `"pong: <input>"`。
 */
char *proxy_pong(const char *input);

/**
 * 释放由本库分配的 C 字符串。
 *
 * Dart 端应优先用 `calloc.free()` 释放，这里只是为了对称。
 *
 * # Safety
 *
 * `ptr` 必须是由本库的某个返回 `*mut c_char` 的函数返回的指针，或者为 NULL。
 */
void proxy_free_string(char *ptr);

/**
 * 启动代理引擎（异步，不阻塞调用线程）。
 *
 * # Arguments
 *
 * * `config_path` - Clash YAML 配置文件路径
 * * `cwd` - 工作目录（用于解析相对路径）
 * * `log_file` - 可选日志文件路径，NULL 表示仅控制台输出
 *
 * # Returns
 *
 * 0 成功，负数失败（错误码见 `ErrorCode`）。
 *
 * # Safety
 *
 * 所有指针必须是合法的 UTF-8 C 字符串，或者为 NULL。
 */
int32_t proxy_engine_start(const char *config_path, const char *cwd, const char *log_file);

/**
 * 停止代理引擎。阻塞最多 5 秒等后台线程退出。
 */
int32_t proxy_engine_stop(void);

/**
 * 查询引擎是否在运行。
 *
 * # Returns
 *
 * 1 = 运行中, 0 = 未运行, 负数 = 错误。
 */
int32_t proxy_engine_is_running(void);

/**
 * 查询引擎详细状态（JSON 字符串）。
 *
 * 返回的指针需要 `libc::free()` 释放。
 */
char *proxy_engine_status(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* CORE_BRIDGE_H */
